export const DEMARCHES = [
  {
    id: 1,
    titre: "Titre de séjour",
    description: "Obtenez votre titre de séjour pour résider légalement en France.",
    priorite: "urgent",
    statut: "termine",
    progression: 100,
    dependances: [],
    delai: "2-3 mois",
    organisme: "Préfecture",
    lienOfficiel: "https://www.service-public.fr/particuliers/vosdroits/N110",
    documents: ["Passeport", "Visa", "Justificatif de domicile", "Photos d'identité"],
    etapes: [
      { id: 1, nom: "Prendre rendez-vous en ligne", statut: "termine" },
      { id: 2, nom: "Préparer le dossier", statut: "termine" },
      { id: 3, nom: "Se présenter en préfecture", statut: "termine" },
      { id: 4, nom: "Récupérer le titre", statut: "termine" },
    ],
  },
  {
    id: 2,
    titre: "Sécurité sociale (CPAM)",
    description: "Inscrivez-vous à l'Assurance Maladie pour bénéficier des remboursements de soins.",
    priorite: "urgent",
    statut: "en_cours",
    progression: 50,
    dependances: [],
    delai: "3-6 semaines",
    organisme: "CPAM",
    lienOfficiel: "https://www.ameli.fr",
    documents: ["Titre de séjour", "RIB", "Justificatif d'identité", "Justificatif de domicile"],
    etapes: [
      { id: 1, nom: "Créer un compte Ameli", statut: "termine" },
      { id: 2, nom: "Envoyer le dossier d'inscription", statut: "en_cours" },
      { id: 3, nom: "Recevoir la carte Vitale", statut: "a_faire" },
      { id: 4, nom: "Choisir un médecin traitant", statut: "a_faire" },
    ],
  },
  {
    id: 3,
    titre: "Compte bancaire",
    description: "Ouvrez un compte bancaire en France pour gérer vos finances localement.",
    priorite: "importante",
    statut: "bloque",
    progression: 0,
    dependances: [2],
    delai: "1-2 semaines",
    organisme: "Banque",
    lienOfficiel: "https://www.service-public.fr",
    documents: ["Titre de séjour", "Justificatif de domicile", "RIB étranger"],
    etapes: [
      { id: 1, nom: "Choisir une banque", statut: "a_faire" },
      { id: 2, nom: "Prendre rendez-vous", statut: "a_faire" },
      { id: 3, nom: "Apporter les documents", statut: "a_faire" },
      { id: 4, nom: "Activer la carte bancaire", statut: "a_faire" },
    ],
  },
  {
    id: 4,
    titre: "CAF – Aide au logement",
    description: "Demandez les aides au logement (APL, ALS) auxquelles vous avez droit.",
    priorite: "urgent",
    statut: "a_faire",
    progression: 0,
    dependances: [3],
    delai: "4-8 semaines",
    organisme: "CAF",
    lienOfficiel: "https://www.caf.fr",
    documents: ["RIB français", "Contrat de bail", "Avis d'imposition", "Titre de séjour"],
    etapes: [
      { id: 1, nom: "Créer un espace CAF", statut: "a_faire" },
      { id: 2, nom: "Simuler les droits", statut: "a_faire" },
      { id: 3, nom: "Déposer la demande", statut: "a_faire" },
      { id: 4, nom: "Recevoir la notification", statut: "a_faire" },
    ],
  },
  {
    id: 5,
    titre: "Mutuelle santé",
    description: "Souscrivez à une mutuelle complémentaire pour être mieux couvert.",
    priorite: "importante",
    statut: "a_faire",
    progression: 0,
    dependances: [2],
    delai: "1 semaine",
    organisme: "Mutuelle privée",
    lienOfficiel: "https://www.complementaire-sante-solidaire.gouv.fr",
    documents: ["Numéro de Sécurité sociale", "RIB"],
    etapes: [
      { id: 1, nom: "Comparer les offres", statut: "a_faire" },
      { id: 2, nom: "Souscrire en ligne", statut: "a_faire" },
      { id: 3, nom: "Transmettre la carte à votre médecin", statut: "a_faire" },
    ],
  },
  {
    id: 6,
    titre: "Inscription Pôle emploi",
    description: "Inscrivez-vous à France Travail pour bénéficier de l'accompagnement emploi.",
    priorite: "optionnelle",
    statut: "a_faire",
    progression: 0,
    dependances: [],
    delai: "Immédiat",
    organisme: "France Travail",
    lienOfficiel: "https://www.francetravail.fr",
    documents: ["Titre de séjour", "CV", "Attestation employeur"],
    etapes: [
      { id: 1, nom: "S'inscrire en ligne", statut: "a_faire" },
      { id: 2, nom: "Entretien de situation", statut: "a_faire" },
      { id: 3, nom: "Valider le projet professionnel", statut: "a_faire" },
    ],
  },
]

export const NOTIFICATIONS = [
  { id: 1, type: "urgent",  message: "Votre titre de séjour expire dans 30 jours.", date: "Aujourd'hui", lu: false },
  { id: 2, type: "doc",     message: "Il manque un document pour votre dossier CPAM.", date: "Hier", lu: false },
  { id: 3, type: "info",    message: "Nouvelle démarche débloquée : Compte bancaire.", date: "Il y a 2 jours", lu: true },
  { id: 4, type: "info",    message: "Votre progression globale est à 36%.", date: "Il y a 3 jours", lu: true },
]

export const PROFILS = [
  { value: "etudiant",    label: "Étudiant(e) étranger(e)", emoji: "🎓" },
  { value: "salarie",     label: "Salarié(e) expatrié(e)",  emoji: "💼" },
  { value: "au_pair",     label: "Au pair / Volontaire",    emoji: "🏠" },
  { value: "resident",    label: "Nouveau résident",        emoji: "👨‍👩‍👧" },
  { value: "professionnel",label: "Professionnel mobile",   emoji: "🌍" },
]
